[build]
  publish = "public"

# These redirects use the Netlify Image CDN to transform images.
#
# For each redirect, if a particular transformation option is not provided
# (e.g., format or quality), it's because the default is good enough and I'm not
# worried about the default being changed to something unreasonable in the
# future. For example, I don't specify quality because the default is currently
# 75, which I think makes sense, and I'm sure Netlify is never going to change
# the default to something ridiculous in the future, like 10.
#
# See the following page for the current default values:
# https://docs.netlify.com/build/image-cdn/overview/#position
#
# It's worth noting that the format of the generated image may depend on how the
# image was loaded. For example, if the image was loaded because the URL of the
# image was the "src" of an "img" tag, the generated image may be in the WebP
# format. On the other hand, if the URL is navigated to directly (e.g., because
# the "Open Image in New Tab" context menu item was clicked), the generated
# image may be in in the format of the original image. That's because browsers
# send different "Accept" headers depending on how a URL is fetched. For
# example, in the former case, the "Accept" header may include "image/webp"
# whereas in the latter case, it may not, because the browser can't know in
# advance that it will be fetching an image.

# Format: Blog default
#
# At the time of this writing, the blog has a fixed width of 640 pixels, hence
# the width of 640.
[[redirects]]
  from = "/blog/posts/:year/:month/:slug/variants/default/:filename"
  to = "/.netlify/images?url=/blog/posts/:year/:month/:slug/original/:filename&w=640&fit=contain"
  status = 302

# Format: Blog lossless
#
# At the time of this writing, the blog has a fixed width of 640 pixels, hence
# the width of 640.
[[redirects]]
  from = "/blog/posts/:year/:month/:slug/variants/lossless/:filename"
  to = "/.netlify/images?url=/blog/posts/:year/:month/:slug/original/:filename&w=640&fit=contain&q=100"
  status = 302

# There is no "one size fits all" format or size for favicons, but the image
# created by this redirect should be _good enough_ for production use. It's also
# a good source image that one could upload to a favicon generator like
# RealFaviconGenerator if they wanted to create and publish several different
# favicons for different platforms.
#
# https://stackoverflow.com/a/48969053/715866
# https://favicon.im/blog/complete-favicon-size-format-guide-2025
# https://realfavicongenerator.net/
[[redirects]]
  from = "/blog/meta/variants/favicon"
  to = "/.netlify/images?url=/blog/meta/original/cropped.jpg&w=512&h=512&fit=cover&position=center&fm=png"
  status = 302

# Similarly, there is no "one size fits all" format or size for social images,
# but the image created by this redirect should be _good enough_ for production
# use, and it's likewise a good source image for a social image generator.
#
# I don't love the way the image looks with any of the crops Netlify can apply
# (e.g., top or center), so at the time of this writing, I actually cropped the
# image manually in an image editor and used that as my social image, rather
# than using the image generated by this redirect. The image I created is not
# cropped exactly preserving the top or exactly preserving the center, but
# rather preserves some area between the top and the center.
#
# https://blog.hootsuite.com/social-media-image-sizes-guide/
[[redirects]]
  from = "/blog/meta/variants/social"
  to = "/.netlify/images?url=/blog/meta/original/cropped.jpg&w=1920&h=1080&fit=cover&position=top&fm=jpg"
  status = 302

# Cache stable URLs (URLs which redirect to /.netlify/images...) for one month.
#
# This way, I can change the settings for a variant (e.g., changing "default"
# from w=640 to w=900), and the changes will apply for all users within one
# month. That may sound like a long time, but it's not as if any changes would
# be dramatic. I may just choose to make images larger or smaller, for example.
# That's fine, especially because images that are too large will be scaled down
# to fit within the width of the blog post.
#
# I do _not_ need to create a "v2" version of each image when I change the
# settings of a variant, because CDNs and browsers typically treat paths with
# different query parameters as different cache entries, and the query
# parameters of the target would be changing (again, from w=640 to w=900 in my
# example).
#
# I wish there were a way to make these paths more generic, so that I don't need
# to have one entry for blog posts, one entry for meta images, and so on.
# However, I don't know of a way to achieve that without changing the URL
# structure. Wildcards appear to only work at the end of a path, so a value like
# "*/variants/*" would not work as expected.
[[headers]]
  for = "/blog/posts/:year/:month/:slug/variants/:variant/:filename"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
[[headers]]
  for = "/blog/meta/variants/:type"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

# Cache images themselves (the content returned from /.netlify/images...) for
# one year.
#
# One might be tempted to apply these headers to the /.netlify/images path, but
# that does not work. Rather /.netlify/images can be thought of as a function
# that loads the image specified by the "url" query parameter and also re-uses
# the Cache-Control headers of the image specified by the "url" query parameter.
# That's why these headers are applied to the _source_ images, not
# /.netlify/images.
#
# Because "immutable" is specified, changing the name of the file is necessary
# to bust the cache. That is, if I change an image and I want to see that change
# take effect on whatever web pages are using the image, I should rename the
# file (e.g., example.v1.jpg -> example.v2.jpg) and update the web page to use
# that new filename.
#
# As mentioned above, I do _not_ need to create a "v2" version of each image
# when I change the settings of a _variant_, because CDNs and browsers typically
# treat paths with different query parameters as different cache entries, and
# the query parameters of the target would be changing (again, from w=640 to
# w=900 in my example).
#
# That means I could probably bust the cache of all images at once, if needed,
# by having the redirects append a version query parameter (e.g., "v=v1") which
# changes whenever I want to bust the cache. However, others say this shouldn't
# be relied upon. I'm using the Netlify CDN, which will definitely treat paths
# differently if they have different "w" or "h" query parameters, for example,
# but it might not treat paths with different "v" query parameters differently.
#
# The "Vary: Accept" header tells clients (CDNs and browsers) to create separate
# cache entries based on the "Accept" header provided in the request. This is
# important because Netlify reads the "Accept" header of the request to
# determine what kind of image it should return. For example, if the "Accept"
# header of the request contains "image/webp", Netlify might return a WebP
# image, whereas if the header doesn't include "image/webp", it might return
# a JPG image. We don't want WebP images and JPG images to be treated as the
# same for caching purposes, which is why we need this "Vary: Accept" header. If
# this were not set, the first user to load an image might get a JPG because
# that's all their browser supports, and all subsequent visitors would also get
# JPGs because the "Accept" header of the request would not be considered when
# the CDN is creating and using caches.
#
# I wish there were a way to make these paths more generic, so that I don't need
# to have one entry for blog posts, one entry for meta images, and so on.
# However, I don't know of a way to achieve that without changing the URL
# structure. Wildcards appear to only work at the end of a path, so a value like
# "*/variants/*" would not work as expected.
[[headers]]
  for = "/blog/posts/:year/:month/:slug/original/:filename"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Vary = "Accept"
[[headers]]
  for = "/blog/meta/original/:filename"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Vary = "Accept"
